/*
 * Assembles the two shipped files from src/.
 *
 *   ghost-light.html   the Claude Artifact source. A FRAGMENT: no
 *                      doctype, <html>, <head> or <body>, because the
 *                      artifact host supplies that shell itself.
 *   index.html         the GitHub Pages entry point. The same content
 *                      wrapped in a real document, because served raw
 *                      over Pages with no <meta name="viewport"> a
 *                      phone lays it out at ~980px and zooms out —
 *                      which wrecks the one thing the interface is
 *                      built around, a command deck sized for a thumb.
 *
 * Both are generated and committed. Edit src/, never the output.
 *
 * The app has to ship as a single self-contained file: to sync, the
 * running page captures its own markup, stylesheet and script and
 * republishes them. So the source is split for humans and inlined
 * for the browser, rather than loaded as separate assets.
 *
 *   node build.js           write both files
 *   node build.js --check   fail if either is out of date (CI)
 */
"use strict";
const fs = require("fs");
const path = require("path");

const SRC = path.join(__dirname, "src");
const PARTS = path.join(SRC, "parts");

function read(p){ return fs.readFileSync(p, "utf8"); }

function assemble(){
  const head  = read(path.join(SRC, "head.html")).trim();
  const css   = read(path.join(SRC, "style.css")).trim();
  const body  = read(path.join(SRC, "body.html")).trim();
  const show  = JSON.parse(read(path.join(SRC, "show.json")));

  // Filename order is load order. Each part is a section of one IIFE
  // and they share a scope, so 00-boot must come first.
  const parts = fs.readdirSync(PARTS).filter(f => f.endsWith(".js")).sort();
  const app = parts
    .map(f => "/* ===== src/parts/" + f + " ===== */\n" + read(path.join(PARTS, f)).trim())
    .join("\n\n");

  const state = JSON.stringify(show).replace(/</g, "\\u003c");

  return [
    head,
    '<style id="sheet">',
    css,
    "</style>",
    "",
    body,
    "",
    '<script id="state" type="application/json">' + state + "</script>",
    "",
    '<script id="app">',
    '(function(){',
    '"use strict";',
    app,
    "})();",
    "</script>",
    ""
  ].join("\n");
}

function page(fragment){
  const MARKER = '<div id="root">';
  const at = fragment.indexOf(MARKER);
  if (at < 0) throw new Error("could not find " + MARKER + " in the assembled fragment");
  return [
    "<!doctype html>",
    '<html lang="en">',
    "<head>",
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">',
    '<meta name="color-scheme" content="light dark">',
    '<meta name="description" content="Live set-piece tracker for a theatre crew: the stage manager calls a scene and every phone follows an animated ground plan of what moves where.">',
    "<!-- Generated by build.js from src/. Do not edit by hand. -->",
    fragment.slice(0, at).trim(),
    "</head>",
    "<body>",
    fragment.slice(at).trim(),
    "</body>",
    "</html>",
    ""
  ].join("\n");
}

const fragment = assemble();
const outputs = [
  [path.join(__dirname, "ghost-light.html"), fragment],
  [path.join(__dirname, "index.html"), page(fragment)]
];

if (process.argv.includes("--check")) {
  let stale = [];
  for (const [file, want] of outputs) {
    let have = null;
    try { have = read(file); } catch (e) { /* missing */ }
    if (have !== want) stale.push(path.basename(file));
  }
  if (stale.length) {
    console.error(stale.join(" and ") + " out of date with src/.");
    console.error("Run: node build.js   (then commit the result)");
    process.exit(1);
  }
  console.log("ghost-light.html and index.html are up to date.");
} else {
  for (const [file, want] of outputs) {
    fs.writeFileSync(file, want);
    console.log("wrote " + path.basename(file) + " (" + want.length + " bytes)");
  }
}
