/*
 * Generates index.html (the GitHub Pages entry point) from ghost-light.html.
 *
 * ghost-light.html is authored as a FRAGMENT: no doctype, <html>, <head> or
 * <body>, because the Claude Artifact host supplies that shell itself. Served
 * raw over Pages it would still render, but with no <meta name="viewport"> a
 * phone lays it out at ~980px and zooms out — which wrecks the one thing the
 * interface is built around, a command deck sized for a thumb.
 *
 * So Pages gets a properly wrapped document instead. The fragment stays the
 * single source of truth; this only adds the shell around it.
 *
 *   node build-pages.js           write index.html
 *   node build-pages.js --check   fail if index.html is out of date (CI)
 */
"use strict";
const fs = require("fs");
const path = require("path");

const SRC = path.join(__dirname, "ghost-light.html");
const OUT = path.join(__dirname, "index.html");
const MARKER = '<div id="root">';

function build() {
  const frag = fs.readFileSync(SRC, "utf8");
  const at = frag.indexOf(MARKER);
  if (at < 0) throw new Error("could not find " + MARKER + " in ghost-light.html");

  const head = frag.slice(0, at).trim();   // title, font links, stylesheet
  const body = frag.slice(at).trim();      // markup + state + app

  return [
    "<!doctype html>",
    '<html lang="en">',
    "<head>",
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    '<meta name="color-scheme" content="light dark">',
    '<meta name="description" content="Live set-piece tracker for a theatre crew: the stage manager calls a scene and every phone follows an animated ground plan of what moves where.">',
    "<!-- Generated by build-pages.js from ghost-light.html. Do not edit by hand. -->",
    head,
    "</head>",
    "<body>",
    body,
    "</body>",
    "</html>",
    ""
  ].join("\n");
}

const built = build();
const check = process.argv.includes("--check");

if (check) {
  let current = null;
  try { current = fs.readFileSync(OUT, "utf8"); } catch (e) { /* missing */ }
  if (current !== built) {
    console.error("index.html is out of date with ghost-light.html.");
    console.error("Run: node build-pages.js   (then commit index.html)");
    process.exit(1);
  }
  console.log("index.html is up to date.");
} else {
  fs.writeFileSync(OUT, built);
  console.log("wrote index.html (" + built.length + " bytes)");
}
